In [3]:
with open('One.txt') as mytext:
    a = mytext.read()

In [4]:
a

'This is a story about dogs\nour canine pets\nDogs are furry animals\n'

In [5]:
with open('One.txt') as mytext:
    words_one = mytext.read().lower().split()
    uni_words_one = set(words_one)

In [6]:
uni_words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [7]:
with open('Two.txt') as mytext:
    words_two = mytext.read().lower().split()
    uni_words_two = set(words_two)

In [8]:
uni_words_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [9]:
all_uni_words = set()
all_uni_words.update(uni_words_one)

In [11]:
all_uni_words.update(uni_words_two)

In [12]:
all_uni_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [13]:
full_vocab = dict()
i = 0

for word in all_uni_words:
    full_vocab[word] = i
    i = i + 1

In [14]:
full_vocab

{'about': 0,
 'are': 1,
 'is': 2,
 'canine': 3,
 'fun': 4,
 'this': 5,
 'pets': 6,
 'sport': 7,
 'dogs': 8,
 'animals': 9,
 'surfing': 10,
 'furry': 11,
 'waves': 12,
 'story': 13,
 'a': 14,
 'water': 15,
 'catching': 16,
 'popular': 17,
 'our': 18}

In [15]:
one_freq = [0] * len(full_vocab)
two_freq = [0] * len(full_vocab)
all_words = ['']*len(full_vocab)

In [16]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [17]:
with open('One.txt') as f:
    one_text = f.read().lower().split()

In [18]:
one_text

['this',
 'is',
 'a',
 'story',
 'about',
 'dogs',
 'our',
 'canine',
 'pets',
 'dogs',
 'are',
 'furry',
 'animals']

In [19]:
for word in one_text:
    word_ind = full_vocab[word]
    one_freq[word_ind] += 1

In [20]:
one_freq

[1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1]

In [29]:
with open('Two.txt') as f:
    two_text = f.read().lower().split()

In [30]:
two_text

['this',
 'story',
 'is',
 'about',
 'surfing',
 'catching',
 'waves',
 'is',
 'fun',
 'surfing',
 'is',
 'a',
 'popular',
 'water',
 'sport']

In [31]:
two_freq

[1, 0, 3, 0, 1, 1, 0, 1, 0, 0, 2, 0, 1, 1, 1, 1, 1, 1, 0]

In [32]:
for word in two_text:
    word_ind = full_vocab[word]
    two_freq[word_ind] += 1

In [33]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [34]:
for word in full_vocab:
    word_ind = full_vocab[word]
    all_words[word_ind]=word

In [35]:
all_words

['about',
 'are',
 'is',
 'canine',
 'fun',
 'this',
 'pets',
 'sport',
 'dogs',
 'animals',
 'surfing',
 'furry',
 'waves',
 'story',
 'a',
 'water',
 'catching',
 'popular',
 'our']

In [36]:
import pandas as pd
bow = pd.DataFrame([one_freq,two_freq],columns=all_words)

In [37]:
bow

about  are  is  canine  fun  this  pets  sport  dogs  animals  surfing  \
0      1    1   1       1    0     1     1      0     2        1        0   
1      2    0   6       0    2     2     0      2     0        0        4   

   furry  waves  story  a  water  catching  popular  our  
0      1      0      1  1      0         0        0    1  
1      0      2      2  2      2         2        2    0

### Utilizing Scikit Learn

In [38]:
text = ['This is a line',
       'This is another line',
       'Completely different line']

In [39]:
from sklearn.feature_extraction.text import CountVectorizer

In [49]:
cv = CountVectorizer()

In [50]:
sparse_matrix = cv.fit_transform(text)

In [51]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [52]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [44]:
#cv = CountVectorizer(stop_words='english')

In [45]:
#sparse_matrix = cv.fit_transform(text)

In [46]:
#sparse_matrix.todense()

matrix([[0, 0, 1],
        [0, 0, 1],
        [1, 1, 1]], dtype=int64)

In [47]:
#cv.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

In [48]:
from sklearn.feature_extraction.text import TfidfTransformer

In [57]:
tfidf = TfidfTransformer()

In [58]:
results = tfidf.fit_transform(sparse_matrix) # BOW --> TF-IDF

In [59]:
results

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [60]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [61]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [62]:
tv = TfidfVectorizer()

In [63]:
tv_results = tv.fit_transform(text)

In [64]:
tv_results

<3x6 sparse matrix of type '<class 'numpy.float64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [65]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])